### ISSUE TITLE
Integrate Examples with vue-live

### ISSUE THREAD

**Issue by elevatebart** [f3ltron/vuepress-plugin-docgen#1]
It would be awesome if we could live edit each example described in docgen.

**Comment by elevatebart** [comment]
Here is a link to [vue-live](https://github.com/vue-styleguidist/vue-live) I will create a PR

**Comment by elevatebart** [comment]
I believe I have a branch working.
Still need to style it and adjust details.

**Comment by flozero** [comment]
maintenant l'environnement de dev est un peu simplifier par rapport a avant il me reste a re ecrire la doc et je pense qu'on pourra dire que nous sommes ok
