### ISSUE TITLE
bad url

### ISSUE THREAD

**Issue by elevatebart** [f3ltron/vuepress-plugin-docgen#11]
the url on the readme of the repo at the top should be https://f3ltron.github.io/vuepress-plugin-docgen/

**Comment by JessicaSachs** [comment]
~~Lol I was just about to report this. I'll submit a PR...~~

Edit: Whoops. I see that the commit above is a fix onto a separate branch to fix this 😅 ... sorry for the confusion! I closed out the PR.

**Comment by flozero** [comment]
thx jessica for that :) yeah the fix will be merge today :)

**Comment by flozero** [comment]
refering to last release :) i close the issue
