### ISSUE TITLE
Need feedback. Should we consider wrapping a component into an iframe?

### ISSUE THREAD

**Issue by flozero** [f3ltron/vuepress-plugin-docgen#36]
I am back and ready to improve the plugin !

My first question is do we need to wrap the component into an iframe?

iframe is good because:
- scope css
- scope component

**Comment by flozero** [comment]
Or maybe you have ideas to full reset css into a div ?

**Comment by elevatebart** [comment]
In my experience, iframes have issues with

1. VueJs and other Dev Tools
1. Needing a server to load
1. Communicating with the main frame

If the target is to scope `css` and scope `components` why not use scoped css or css-modules?
If the objective is to have an iframe anyway, why not use another code-sandbox plugin instead?

**Comment by flozero** [comment]
I did some write with codesandbox.

I think the second i wanted to think about is to catch actions as storybook does
