### ISSUE TITLE
Any vuepress plugin should start with `vuepress-plugin-`

### ISSUE THREAD

**Issue by elevatebart** [f3ltron/vuepress-plugin-docgen#7]
We might have to change  the name of the package to

`vuepress-plugin-docgen`

if we want to resolve it with string only.

today we have to configure it like so: 

```js
module.exports = {
  plugins: [
    [
      require("vuepress-component-docgen")
    ]
  ]
}
```

I would rather have this

```js
module.exports = {
  plugins: [
    [
      'docgen'
    ]
  ]
}
```

**Comment by flozero** [comment]
It will be correct with the #1
